function laserCam()

    global vid;
    brightness = 0;
    
    if ispc()
        % 'FrameRate','30',... % only works in Format 0
        set(vid.Source,...
          'AutoExposure',0,...
          'Brightness',brightness,...
          'Gain', 0,...
          'Sharpness', 0,...
          'Shutter', shutter1394(1250*2),...
          'ShutterMode','manual');
    elseif isunix()
        
        runningFlag = false;
        if strcmp(vid.Running,'on')
            runningFlag = true;
            stop(vid);
        end
        
        set(vid.Source,...
          'Exposure',0,...
          'Brightness',brightness,...
          'Gain', 0,...
          'Sharpness', 0,...
          'Shutter', shutter1394(1250*2),...
          'ShutterMode','manual');
      
      if runningFlag
          start(vid);
          trigger(vid);
      end
    end