function setupRemotePHP()

	if isunix()
		[status, currentIP] = system('ip addr show eth0 | grep -Po ''(?<=inet )[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*''');
	else
		disp('Local webserving not setup in Windows, not pushing PHP script.');
		return;
	end

	scriptLines =  {'<?php',...
					'ini_set(''display_errors'', ''On'');',...
					'error_reporting(E_ALL | E_STRICT);',...
					'$ch = curl_init();',...
					'[curl_setopt($ch, CURLOPT_URL, ''http://',currentIP,'/rtfw.html'');'],...
					'curl_setopt($ch, CURLOPT_POST, 1);',...
					'curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);',...
					'curl_setopt($ch, CURLOPT_HEADER, 0);',...
					'curl_setopt($ch, CURLOPT_VERBOSE, true);',...
					'curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);',...
					'curl_setopt($ch, CURLOPT_AUTOREFERER, true);',...
					'curl_setopt($ch, CURLOPT_MAXREDIRS, 10);',...
					'$store = curl_exec($ch);',...
					'$headers = curl_getinfo($ch);',...
					'echo $store;',...
					'?>'};

	fileID = fopen('rtfw.php','w');

	for lineN = 1:size(scriptLines,2)
		fprintf(fileID,'%s',scriptLines{lineN});
	end

	fclose(fileID);

	cmd = 'scp ./rtfw.php jsb38@orchestra.med.harvard.edu:/www/wilson.med.harvard.edu/docroot/';
    
