function exp = laser_cont_noshock_Miesenbock(exp)
   
	laserDistribution = exp.protocolArgs{1};
	laserParams       = exp.protocolArgs{2};

    exp.laserDistribution = laserDistribution;
    exp.laserParams       = laserParams;
    exp.preLEpochs   = [2];
    exp.preREpochs   = [4];
	exp.shockLEpochs  =  [6,10];
	exp.shockREpochs  =  [8,12];
	exp.postLEpochs  =  [14];
	exp.postREpochs  =  [16];
  
    setLaserOff = {@setLaserDistribution,{@laserOff,[]}};
    setLaserL   = {@setLaserDistribution,{laserDistribution,[laserParams(1), laserParams(2)]}};
    setLaserR   = {@setLaserDistribution,{laserDistribution,[laserParams(2), laserParams(1)]}};

	setShockOff  = {@sendToShockController,{0,0}};
	setShockL  =   {@sendToShockController,{0,1}};
	setShockR  =   {@sendToShockController,{0,2}};
    
% Times in minutes
    exp.protocolDesign = {...
        % Time (min), Odor left, odor right, laser left, laser right
[   0, setLaserOff];...
[   1, setLaserL];...
[   3, setLaserOff];...
[   5, setLaserR];...
[   7, setLaserOff];...
[   9, setLaserL];...
[  10, setLaserOff];...
[  11, setLaserR];...
[  12, setLaserOff];...
[  14, setLaserL];...
[  15, setLaserOff];...
[  16, setLaserR];...
[  17, setLaserOff];...
[  22, setLaserL];...
[  24, setLaserOff];...
[  26, setLaserR];...
[  28, setLaserOff];...

};

    exp.nEpochs = size(exp.protocolDesign,1)-1;


