function exp = laser_OL_one_sec_toggles(exp)
   
	laserDistribution = exp.protocolArgs{1};
	laserParams       = exp.protocolArgs{2};

    exp.laserDistribution = laserDistribution;
    exp.laserParams       = laserParams;
    exp.nullEpochs   = [1,32];
    exp.leftEpochs   = [2:2:30];
	exp.rightEpochs  = [3:2:31];
  
    setLaserOff =  {@setLaserDistribution,{@laserOff,[]}};
    setLaserL    =  {@setLaserDistribution,{laserDistribution,laserParams([1,2,3,4])}};
    setLaserR    =  {@setLaserDistribution,{laserDistribution,laserParams([2,1,4,3])}};
    latencyLowLaserOff  =  {@setBestLatency,true, @setLaserDistribution,{@laserOff,[]}};
    laserOfflatencyHigh =  {@setLaserDistribution,{@laserOff,[]}, @setBestLatency,false};
    
% Times in minutes
    exp.protocolDesign = {...
        % Time (min), Odor left, odor right, laser left, laser right
[   0,   latencyLowLaserOff];...
[   1 + ( 0/60),   setLaserL];...
[   1 + ( 1/60),   setLaserR];...
[   1 + ( 2/60),   setLaserL];...
[   1 + ( 3/60),   setLaserR];...
[   1 + ( 4/60),   setLaserL];...
[   1 + ( 5/60),   setLaserR];...
[   1 + ( 6/60),   setLaserL];...
[   1 + ( 7/60),   setLaserR];...
[   1 + ( 8/60),   setLaserL];...
[   1 + ( 9/60),   setLaserR];...
[   1 + (10/60),   setLaserL];...
[   1 + (11/60),   setLaserR];...
[   1 + (12/60),   setLaserL];...
[   1 + (13/60),   setLaserR];...
[   1 + (14/60),   setLaserL];...
[   1 + (15/60),   setLaserR];...
[   1 + (16/60),   setLaserL];...
[   1 + (17/60),   setLaserR];...
[   1 + (18/60),   setLaserL];...
[   1 + (19/60),   setLaserR];...
[   1 + (20/60),   setLaserL];...
[   1 + (21/60),   setLaserR];...
[   1 + (22/60),   setLaserL];...
[   1 + (23/60),   setLaserR];...
[   1 + (24/60),   setLaserL];...
[   1 + (25/60),   setLaserR];...
[   1 + (26/60),   setLaserL];...
[   1 + (27/60),   setLaserR];...
[   1 + (28/60),   setLaserL];...
[   1 + (29/60),   setLaserR];...
[   1 + (30/60), setLaserOff];...
[   2.5, laserOfflatencyHigh];...

};

    exp.nEpochs = size(exp.protocolDesign,1)-1;


