function exp = laser_1_2L_1_2Rx4(exp)
   
	laserDistribution = exp.protocolArgs{1};
	laserParams       = exp.protocolArgs{2};

    exp.laserDistribution = laserDistribution;
    exp.laserParams       = laserParams;
    exp.nullEpochs   = [1];
    exp.leftEpochs   = [2];
	exp.rightEpochs  =  [];
  
    setLaserOff = {@setLaserDistribution,{@laserOff,[]}};
    setLaserL   = {@setLaserDistribution,{laserDistribution,[laserParams(1), laserParams(2)]}};
    setLaserR   = {@setLaserDistribution,{laserDistribution,[laserParams(2), laserParams(1)]}};
    
% Times in minutes
    exp.protocolDesign = {...
        % Time (min), Odor left, odor right, laser left, laser right
[   0, setLaserOff];...
[   1, setLaserL];...
[   5, setLaserOff];...
[   6, setLaserR];...
[   8, setLaserOff];...
[   9, setLaserL];...
[  11, setLaserOff];...
[  12, setLaserR];...
[  14, setLaserOff];...
[  15, setLaserL];...
[  17, setLaserOff];...
[  18, setLaserR];...
[  20, setLaserOff];...
[  21, setLaserL];...
[  23, setLaserOff];...
[  24, setLaserR];...
[  26, setLaserOff];...


};

    exp.nEpochs = size(exp.protocolDesign,1)-1;


