function exp = laser_OL_half_sec(exp)
   
	laserDistribution = exp.protocolArgs{1};
	laserParams       = exp.protocolArgs{2};
	pulseDuration = .05; % sec

    exp.laserDistribution = laserDistribution;
    exp.laserParams       = laserParams;
    exp.nullEpochs   = [1:2:17];
    exp.leftEpochs   = [2:2:16];
	exp.rightEpochs  = [2:2:16];
  
    setLaserOff =  {@setLaserDistribution,{@laserOff,[]}};
    setLaser    =  {@setLaserDistribution,{laserDistribution,laserParams}};
    latencyLowLaserOff  =  {@setBestLatency,true, @setLaserDistribution,{@laserOff,[]}};
    laserOfflatencyHigh =  {@setLaserDistribution,{@laserOff,[]}, @setBestLatency,false};
    
% Times in minutes
    exp.protocolDesign = {...
        % Time (min), Odor left, odor right, laser left, laser right
[    0,   latencyLowLaserOff];...
[   .25*1,   setLaser];...
[   .25*1+(pulseDuration/60), setLaserOff];...
[   .25*2,   setLaser];...
[   .25*2+(pulseDuration/60), setLaserOff];...
[   .25*3,   setLaser];...
[   .25*3+(pulseDuration/60), setLaserOff];...
[   .25*4,   setLaser];...
[   .25*4+(pulseDuration/60), setLaserOff];...
[   .25*5,   setLaser];...
[   .25*5+(pulseDuration/60), setLaserOff];...
[   .25*6,   setLaser];...
[   .25*6+(pulseDuration/60), setLaserOff];...
[   .25*7,   setLaser];...
[   .25*7+(pulseDuration/60), setLaserOff];...
[   .25*8,   setLaser];...
[   .25*8+(pulseDuration/60), setLaserOff];...
[   2.5, laserOfflatencyHigh];...

};

    exp.nEpochs = size(exp.protocolDesign,1)-1;


