function exp = laser_cont_shock_Miesenbock(exp)
   
	laserDistribution = exp.protocolArgs{1};
	laserParams       = exp.protocolArgs{2};

    exp.laserDistribution = laserDistribution;
    exp.laserParams       = laserParams;
    exp.preLEpochs   = [2];
    exp.preREpochs   = [];
	exp.shockLEpochs  =  [4,8];
	exp.shockREpochs  =  [6,10];
	exp.postLEpochs  =  [14];
	exp.postREpochs  =  [12];
  
    setLaserOff = {@setLaserDistribution,{@laserOff,[]}};
    setLaserL   = {@setLaserDistribution,{laserDistribution,[laserParams(1), laserParams(2)]}};
    setLaserR   = {@setLaserDistribution,{laserDistribution,[laserParams(2), laserParams(1)]}};

	setShockOff  = {@sendToShockController,{0,0}};
	setShockL  =   {@sendToShockController,{0,1}};
	setShockR  =   {@sendToShockController,{0,2}};
    
% Times in minutes
    exp.protocolDesign = {...
        % Time (min), Odor left, odor right, laser left, laser right
[   0, setLaserOff];...
[   1, setLaserL];...
[   3, setLaserOff];...
[   5, [setLaserL,setShockL]];...
[   6, [setLaserOff,setShockOff]];...
[   7, [setLaserR,setShockR]];...
[   8, [setLaserOff,setShockOff]];...
[  10, [setLaserL,setShockL]];...
[  11, [setLaserOff,setShockOff]];...
[  12, [setLaserR,setShockR]];...
[  13, [setLaserOff,setShockOff]];...
[  18, setLaserR];...
[  20, setLaserOff];...
[  22, setLaserL];...
[  24, setLaserOff];...

};

    exp.nEpochs = size(exp.protocolDesign,1)-1;


